#!/usr/bin/env python

# name = input("What is the name of your friend ? ")
# name = str(name)
# print(f"My name is {name}")

names = ["Judah", "Noah", "Joshua", "Tireni"]

for i in range(0, len(names)):
    print(names[i])

for key, value in enumerate(names):
    print(value)

# list operations [*]
groceries = ["milk", "eggs", "bread"]

foods = ["rolls", "pastries"] + groceries
foods.append("rice")
foods.append("yams")
foods.pop()
print(foods)

#list Creation/Comprehension [*] star
newGroceries = [x + " 2kg" for x in foods] 
print(newGroceries)

#list Creation/Comprehension [&] and 
partialGroceries = newGroceries[:3]
print(partialGroceries)
print(foods[:])

print(f"reference of foods list: {id(foods)}")

print(f"size of a food list : {foods.__sizeof__()} bytes")

import pandas as pd
df = pd.DataFrame(columns=['foods','position'])
index = range(0, len(foods))
df['foods'],df['position'] = foods, index
print(df)

# Sets

mySet = {1,2,4,6,6,10,22,4, 8}
mySet.update({3,5,6})
print(mySet)